name: attendance_tracking_system
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_foreground_task: ^8.17.0
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  location: ^7.0.1
  permission_handler: ^11.3.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  geolocator: ^13.0.1
  local_auth: ^2.3.0
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  table_calendar: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/profile_images/abcd@gmail.com.png
    - assets/icons/placeholder.svg
    - assets/login_image.webp
    - assets/login.json
    - assets/profile_images/shruthvik123@gmail.com.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
