// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3EMCKU8yr1CJtTEWJrFV_87zLLNaNY0Q',
    appId: '1:30534150514:android:0d974a5a3b5971788715eb',
    messagingSenderId: '30534150514',
    projectId: 'attendance-tracking-syst-8e60a',
    storageBucket: 'attendance-tracking-syst-8e60a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqACjAX3q-1BvomiTU_JdmZdXa-yKz3Iw',
    appId: '1:30534150514:ios:1911518d31463ae28715eb',
    messagingSenderId: '30534150514',
    projectId: 'attendance-tracking-syst-8e60a',
    storageBucket: 'attendance-tracking-syst-8e60a.firebasestorage.app',
    iosClientId: '30534150514-9it9u8epv3pav4onpks6d2kupe54st1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceTrackingSystem',
  );
}
